CREATE DATABASE shortly;

CREATE TABLE users(
    id  SERIAL NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

CREATE TABLE urls(
    id SERIAL NOT NULL PRIMARY KEY,
    shortUrlTEXT NOT NULL,
    url TEXT NOT NULL,
    userId INTEGER NOT NULL REFERENCES users(id),
    visitCount INTEGER NOT NULL
);

CREATE TABLE sessions(
    id SERIAL NOT NULL PRIMARY KEY,
    userId INTEGER NOT NULL REFERENCES users(id),
    token TEXT NOT NULL UNIQUE
);